import type { CompetitorIntel, CompetitorLeaderboardRow } from '@growthpath/shared';

export const sampleCompetitorIntelFixture: CompetitorIntel = {
  name: 'Goldfield Trading Post',
  domain: 'goldfieldtradingpost.com',
  rating: 4.5,
  review_count: 672,
  da: 35,
  referring_domains: 120,
  gbp_category: 'hamburger_restaurant',
  frequency_near_me: 8,
  frequency_city: 5,
  why_winning:
    '<strong>Review volume is the primary gap.</strong> Goldfield Trading Post has 672 reviews vs. your 679.',
  surface_positions: {
    burgers: {
      maps_nm: 1,
      lf_nm: 1,
      maps_city: 3,
      lf_city: 2,
      client_maps_nm: 2,
      client_lf_nm: 3,
      client_maps_city: 5,
      client_lf_city: 4,
    },
  },
  action_callout: 'Launch a consistent review generation program targeting recent customers',
  client: {
    name: 'Kitchen 747',
    domain: 'kitchen747.com',
    rating: 4.4,
    review_count: 679,
    da: 15,
    referring_domains: 66,
    gbp_category: 'restaurant',
    vis_score: 55,
    appearances: 6,
  },
  visibility: {
    vis_score: 88,
    appearances: 12,
    maps_appearances: 8,
    lf_appearances: 4,
    avg_rank: 2.1,
    frequency_near_me: 8,
    frequency_city: 5,
  },
  deltas: [
    {
      metric: 'reviews',
      label: 'Google reviews',
      clientValue: 679,
      competitorValue: 672,
      delta: -7,
      advantage: 'client',
      formattedClient: '679',
      formattedCompetitor: '672',
      formattedDelta: '-7',
    },
    {
      metric: 'da',
      label: 'Domain authority',
      clientValue: 15,
      competitorValue: 35,
      delta: 20,
      advantage: 'competitor',
      formattedClient: '15',
      formattedCompetitor: '35',
      formattedDelta: '+20',
    },
    {
      metric: 'visibility',
      label: 'Visibility score',
      clientValue: 55,
      competitorValue: 88,
      delta: 33,
      advantage: 'competitor',
      formattedClient: '55',
      formattedCompetitor: '88',
      formattedDelta: '+33',
    },
  ],
  why_factors: ['Domain authority materially higher than client', 'Leads near-me Map Pack 8 times as #1'],
  surface_matrix: [
    {
      service: 'burgers',
      maps_nm: 1,
      lf_nm: 1,
      maps_city: 3,
      lf_city: 2,
      client_maps_nm: 2,
      client_lf_nm: 3,
      client_maps_city: 5,
      client_lf_city: 4,
    },
  ],
  counter_moves: [
    {
      rank: 1,
      pillar: 'P1',
      surface: 'domain',
      action: 'Audit directory citations and pursue high-quality local backlinks',
      rationale: 'Domain authority gap (+20 DA) supports their visibility beyond proximity.',
    },
    {
      rank: 2,
      pillar: 'P1',
      surface: 'visibility',
      action: 'Prioritize Map Pack keywords where the competitor ranks #1 but you are outside top 3',
      rationale: 'Aggregate visibility score trails by +33 points across scanned surfaces.',
    },
  ],
  category_match: false,
  category_advantage: 'competitor',
};

export const sampleCompetitorLeaderboardFixture: CompetitorLeaderboardRow[] = [
  {
    rank: 1,
    domain: 'goldfieldtradingpost.com',
    name: 'Goldfield Trading Post',
    is_client: false,
    is_primary: true,
    appearances: 12,
    maps_appearances: 8,
    lf_appearances: 4,
    avg_rank: 2.1,
    vis_score: 88,
    rating: 4.5,
    review_count: 672,
    da: 35,
    referring_domains: 120,
    category: 'restaurant',
    frequency_near_me: 8,
    frequency_city: 5,
  },
  {
    rank: 2,
    domain: 'kitchen747.com',
    name: 'Kitchen 747',
    is_client: true,
    is_primary: false,
    appearances: 6,
    maps_appearances: 4,
    lf_appearances: 2,
    avg_rank: 5.2,
    vis_score: 55,
    rating: 4.4,
    review_count: 679,
    da: 15,
    referring_domains: 66,
    category: 'restaurant',
    frequency_near_me: 1,
    frequency_city: 0,
  },
];
