import type { Scores } from '@growthpath/shared';
import {
  sampleCompetitorIntelFixture,
  sampleCompetitorLeaderboardFixture,
} from './competitor.fixture.js';

export const sampleScoresFixture: Scores = {
  p1: 42,
  p2: 46,
  profile: 'The Invisible Closer',
  p1_tier: ['Needs Work', '#f59e0b'],
  p2_tier: ['Needs Work', '#f59e0b'],
  categories: {
    gbp_strength: {
      score: 55,
      tier: ['Competitive', '#60a5fa'],
      weight: '20%',
      findings: [{ text: 'GBP profile is incomplete.', severity: 'warning' }],
      category_opportunity: null,
      signal_pts: {},
    },
    mappack: {
      score: 38,
      tier: ['Needs Work', '#f59e0b'],
      weight: '60%',
      findings: [{ text: 'Not visible in the local 3-pack.', severity: 'critical' }],
      scenario: 'invisible',
      kw_3pack: [],
      kw_city_visible: [],
      kw_local_visible: [],
      kw_invisible: ['burgers near me'],
      keyword_scores: {},
      unexpected_3pack: [],
      near_miss: [],
      competitor_leaderboard: [],
      local_reach: 0,
      regional_reach: 0,
      near_me_score: 0,
      city_score: 0,
      diagnosis: 'Low map pack visibility.',
    },
    onpage: {
      score: 62,
      tier: ['Competitive', '#60a5fa'],
      weight: '10%',
      findings: [{ text: 'Service pages are well structured.', severity: 'good' }],
      signal_pts: {},
    },
    trust: {
      score: 48,
      tier: ['Needs Work', '#f59e0b'],
      weight: '10%',
      findings: [{ text: 'Domain authority is below competitors.', severity: 'warning' }],
      signal_pts: {},
    },
    performance: {
      score: 21,
      tier: ['Critical', '#f87171'],
      weight: '35%',
      findings: [{ text: 'Mobile performance is poor.', severity: 'critical' }],
      signal_pts: {},
    },
    conversion: {
      score: 40,
      tier: ['Needs Work', '#f59e0b'],
      weight: '40%',
      findings: [{ text: 'No analytics detected.', severity: 'warning' }],
      signal_pts: {},
    },
    ux: {
      score: 90,
      tier: ['Leading', '#4ade80'],
      weight: '25%',
      findings: [{ text: 'Responsive layout looks strong.', severity: 'good' }],
      signal_pts: {},
    },
  },
  actions: [
    {
      rank: 1,
      pillar: 'P1',
      action: 'Improve map pack visibility for core keywords.',
      effort: 'Medium',
      impact: 'High',
      why_now: 'Competitors dominate local search results.',
    },
  ],
  serp_data: {},
  labs_data: {},
  competitor_intel: sampleCompetitorIntelFixture,
  competitor_leaderboard: sampleCompetitorLeaderboardFixture,
};
